name: flutter_release
description: A tool for building and publishing Flutter apps, e.g. on GitHub, the Google Play Store and Apple's App Store.
version: 0.3.5+1
resolution: workspace
repository: https://github.com/Oberhauser-Dev/dart_packages/tree/main/packages/flutter_release

environment:
  sdk: ^3.6.0

executables:
  flutter_release:

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  flutter_to_debian: ^2.0.2
  dart_release: ^0.2.12+1
  pubspec_parse: ^1.3.0
  pub_semver: ^2.1.4
  path: ^1.9.1
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
